spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wechat?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: xxxxx
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  mail:
    host: smtp.163.com
    port: 25
    username: xxxx
    password: xxxx
    nickname: 微信公众号AI助手
    default-encoding: UTF-8
    properties:
      mail:
        debug: false
        smtp:
          ssl:
            trust: smtp.163.com
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 80
# 自定义微信相关配置信息
aliyun:
  accessKeyId: xxxxxx
  accessKeySecret: xxxx
  agentKey: xxxx
  appId: xxxxx
wx:
  # 消息模板ID
  templateId: xxxxxxxxx
  mp:
    # 微信公众号的appid
    appId: xxxxxxxx
    # 信公众号的app secret
    secret: xxxxxxxx
    # 微信公众号的toke
    token: token
    aesKey: xxxxxxxxx
    config-storage:
      key-prefix: wx
      type: Redisson
      redis:
        host: localhost
        port: 6379





